### PR TITLE
Mjolnir Pull Request

### PR DESCRIPTION
**Pull request by vikramsandhu**
# Mjolnir Pull Request

### Replace ARTIQ dependencies with SiPyCo

- Removed ARTIQ dependencies and replaced them with the (much lighter-weight) SiPyCo equivalents.

### Support for Thorlabs CS165MU1

- Support has been added for the new Thorlabs [CS165MU1](https://www.thorlabs.com/thorproduct.cfm?partnumber=CS165MU1) camera (Thorlabs’ replacement for the now discontinued [DCC1545M](https://www.thorlabs.com/thorproduct.cfm?partnumber=DCC1545M)).

- Support is built using Revision G of the Windows SDK from [Thorlabs](https://www.thorlabs.com/software_pages/ViewSoftwarePage.cfm?Code=ThorCam). The development kit contains the appropriate drivers and DLLs. Installation details were added to the ReadMe.

- The file `mjolnir\drivers\tsi\__init__.py` was created as a controller for Thorlabs Scientific Imaging cameras. It essentially copies the functionality of `mjolnir\drivers\uc480\__init__.py`. This functionality is then passed onto `mjolnir\drivers\camera.py`.

- A notable difference between the two `__init__.py` files is the deletion of the _create_buffer()_ and _get_buffer()_ functions in the TSI file. The TSI drivers contain functions that handle image buffers internally.

- `camera.py` detects whether the connected camera is DCx or TSI, and adjusts functionality accordingly.

- Continuous acquisition is accomplished a bit differently on TSI cameras. Rather than operating the camera in continuous acquisition mode, the camera acquires individual frames at the desired frame rate. This allows for the greatest control over frame rate and exposure parameters. Live adjustments are made to the sleep time between frames, in order to match the measured frame rate to the desired value.

- Another functional difference between DCx and TSI cameras is the frame rate control. For TSI cameras, the frame rate can be controlled directly and the live changes will occur as described above. For DCx cameras, the frame rate can only be controlled indirectly via the pixel clock.

### Save and Load Frames

- Functionality has been added to save and load individual frames from within the GUI.

- This is accomplished by using Python's _pickle_ module to save/load a `.pickle` file containing the dictionary object that stores all relevant image and beam data.

- A [Jupyter Notebook](https://github.com/OregonIons/mjolnir-frame-analyzer) was created to analyze saved frames.

### Updates to GUI

- A spinbox was created that allows the user to vary the frame rate (either directly or indirectly, depending on the camera).

- A label has been added to the exposure spinbox.

- Added a "Reset View" button, which resets the view boxes after zoom/pan adjustments have been made.

- Added "Save Frame" and "Load Frame" buttons to save/load individual frames, as described above.

- Disabled "Start Acquisition" and "Single Acquisition" buttons when continuous acquisition has been started.

- Disabled "Stop Acquisition" button when acquisition has been stopped.

- Edited the layout to make it a bit more intuitive.

### CODE REVIEW

**Comment by dnadlinger** [comment]
Apologies, this took me way longer to get to than it should have. First, thank you very much for also developing your extensions in the open; I really hope sharing technical work like this between groups will be much more common in the future. As for this pull request in particular, it is unfortunately pretty hard to review comprehensively. When preparing pull requests for open-source projects, there are a few things to keep in mind that make reviewing changes much easier, and are hence common practice in open source projects:

Commits should be atomic, in the sense that each of them contains one complete change, and one change only. As much as possible, each commit should be functional, so that if a new bug is found later, it is easy to go back through the history and bisect where it was first introduced. Here, for instance, 9a42d91cf95e5a4077e0ddab109dc20b6571fae3 ("Add files via upload") creates two new files in the wrong place. The files in the right place are later deleted in a3abb546b92d3761d7846c9ee04ff5d1fdc764b0 f., and the new files then moved into the correct location in 9e22ed30ded337e6c8344bc07d2d78a0e948ee90 f. This makes it hard to track what is going on (suddenly, there are hundreds of lines of changes), and also loses history information. Now, I have to manually fetch the PR and locally run `git diff master..96f6e95c39d8cb3f49a44da790287f3928a520cf -- mjolnir/frontend` to uncover the only actual few changes – which are necessary, and very welcome:
```diff
diff --git a/mjolnir/frontend/gui.py b/mjolnir/frontend/gui.py
index aec65ab..36fd27b 100644
--- a/mjolnir/frontend/gui.py
+++ b/mjolnir/frontend/gui.py
@@ -5,7 +5,7 @@ import argparse
 import atexit
 import logging
 from PyQt5 import QtWidgets, QtCore
-from artiq.protocols.pc_rpc import Client
+from sipyco.pc_rpc import Client
 
 from mjolnir.ui.beam import BeamDisplay
 from mjolnir.drivers.camera import Camera, list_serial_numbers
diff --git a/mjolnir/frontend/server.py b/mjolnir/frontend/server.py
index 9647532..504ec05 100644
--- a/mjolnir/frontend/server.py
+++ b/mjolnir/frontend/server.py
@@ -4,8 +4,8 @@ import sys
 import time
 import zmq
 
-from artiq.protocols.pc_rpc import simple_server_loop
-from artiq.tools import simple_network_args, init_logger
+from sipyco.pc_rpc import simple_server_loop
+from sipyco import simple_network_args, init_logger
 from mjolnir.drivers.camera import Camera, list_serial_numbers
 
 # Copy pasted from oxart, since that isn't publicly available
```

If this was a single commit – even better, with a useful commit message (which could be as simple as `artiq.protocols -> sipyco` or `Use SiPyCo instead of old artiq.protocols`) – this would have only taken five seconds seconds to review instead of minutes. Git makes it easy to fix up/combine commits after the fact, see e.g. `git rebase --interactive` – make use of it!

As for commit messages in general, the convention is that the first line should be a very brief, but complete description of what is going on. Here, many commits are just called "Add files via upload", or "Update xyz", which is useless when scrolling through the history (or reviewing the changes).  Again, this can be changed after the fact, using e.g. `git commit --amend` or `git rebase --interactive`. dcf1e1cd05d26001752efbacae6d58d51d255ac3 is supposedly "Added functionality", but doesn't in fact appear to add any functionality (in any case, which?). The three "final update[s] prior to PR" which "[add] comments and [clean] up.", cbc1720, 1817301, and bced712, seem to do more than that and fix some bugs/slightly change some behaviour.  

Spurious changes are also best avoided, as they make it harder to track what is going on, and can cause merge conflicts between branches. For instance, 9fc999f3914e5d3c5cb6164a4fd1b5c22b3dfff9 changes hundreds of lines:
```diff
$ git show --shortstat 9fc999f3914e5d3c5cb6164a4fd1b5c22b3dfff9
commit 9fc999f3914e5d3c5cb6164a4fd1b5c22b3dfff9
Author: vikramsandhu <54603544+vikramsandhu@users.noreply.github.com>
Date:   Mon Jun 22 15:20:35 2020 -0700

    Add files via upload
    
    Added label for exposure time.

 1 file changed, 610 insertions(+), 608 deletions(-)
```

In reality, though, this just converts the file to DOS line endings; ignoring those, the actual change is just two lines!
```diff
$ git show -w 9fc999f3914e5d3c5cb6164a4fd1b5c22b3dfff9
commit 9fc999f3914e5d3c5cb6164a4fd1b5c22b3dfff9
Author: vikramsandhu <54603544+vikramsandhu@users.noreply.github.com>
Date:   Mon Jun 22 15:20:35 2020 -0700

    Add files via upload
    
    Added label for exposure time.

diff --git a/mjolnir/ui/beam.py b/mjolnir/ui/beam.py
index f610bc8..fe8a628 100644
--- a/mjolnir/ui/beam.py
+++ b/mjolnir/ui/beam.py
@@ -340,6 +340,7 @@ class BeamDisplay(QtWidgets.QMainWindow):
         self.start_acq = QtGui.QPushButton("Start Acquisition")
         self.stop_acq = QtGui.QPushButton("Stop Acquisition")
         
+        self.exposure_label = QtGui.QLabel("Exposure Time:")^M
         self.exposure = QtGui.QDoubleSpinBox()
         self.exposure.setSuffix(" ms")
         self.get_exposure_params()
@@ -489,6 +490,7 @@ class BeamDisplay(QtWidgets.QMainWindow):
         self.info_pane_layout.addWidget(self.start_acq)
         self.info_pane_layout.addWidget(self.single_acq)
         self.info_pane_layout.addWidget(self.stop_acq)
+        self.info_pane_layout.addWidget(self.exposure_label)^M
         self.info_pane_layout.addWidget(self.exposure)
         self.info_pane_layout.addStretch(1)
         self.info_pane_layout.addWidget(self.param_widget)
```
Some changes also add trailing whitespace at the end of lines; this is generally frowned upon for the same reason (spurious changes later).

Why was the Python version restricted to 3.7.7 in 2910c40? This is very non-obvious; if there is a good reason, it should be explained in a comment and/or commit message.

Having to manually specify the DLL path by editing a Python file (which shouldn't normally be done when installing as a regular package rather than in development mode) seems a bit silly. Shouldn't this be a command line option/...? To be fair, it seems like it should just work when the SDK is installed to the default location.

In terms of the code itself, all the `self.is_tsi_cam` checks are a bit clunky. Since OOP is natural in Python, this would be a prime opportunity to deploy subclassing. The hardware-specific functions necessary could either be moved into `uc480` and `tsi`, or if not modifying `uc480` is preferred, into new `Camera` subclassses. The corresponding docstrings would then also be a good place to permanently store the comments on the differences between the cameras from the pull request description.

By the way, did you test this with an old uc480 camera as well, or only newer ones?

**Comment by dtcallcock** [comment]
Thank you for this detailed response. 

> I really hope sharing technical work like this between groups will be much more common in the future. 

This is also our hope.  Given my limited Python skillset and supervision capacity, it will take some time for us to develop the institutional knowledge required to make high-quality PRs.  Thanks for bearing with us.

 > By the way, did you test this with an old uc480 camera as well, or only newer ones?

Yes, we have a couple. Thorlabs still had a few in stock last time I checked but will discontinue once they are gone.  You might still be able to get them from the original vendor but we were motivated to add TSI support as we plan to use variouse TSI models with ARTIQ etc and wanted to start figuring out the SDK.

**Comment by vikramsandhu** [comment]
Thank you for reviewing the pull request and for your criticisms. This was essentially my first time doing this sort of thing, and was my first experience with version control. I certainly understand that this pull request is unreadable, and I appreciate you taking the time to explain and give examples. I will be going back and making changes to both the files and the commits, as you suggested.

To address your questions:

Python was restricted to 3.7.7 because I wasn't able to run the software (the current version on the OxfordIonTrapGroup repository, as well as the version in this pull request) using Python 3.8. I believe this was due to one of the dependencies, but I'll have to go back and check. I'll be sure to either change or explain this.

We tested this software with both a uc480 camera and a tsi camera. It still handled the uc480 camera just fine, and the added spinbox for pixel clock gives some level of control over the frame rate.

I agree that manually specifying the DLL path is shaky. I'll move this to a command-line option, or maybe something else.

I will also look into re-organizing and subclassing. I agree that it would make things much cleaner.

**Comment by ljstephenson** [comment]
Sorry for abandoning this! I'll echo @dnadlinger 's sentiments - I really appreciate that you guys are looking to improve something that I hacked together. I think David has covered all the main points on this PR excellently.

I would say that moving hardware specific functions into `uc480` is the way to go, I had originally intended not to modify this too much because I had copied it from https://github.com/ddietze/pyUVVIS. On that note there is also IDS ueye https://pypi.org/project/pyueye/ which is probably a better interface for the uc480 cameras; it may or may not be worth looking at moving to using this instead.

**Comment by hartytp** [comment]
Let's close this PR as being essentially unreviewable as is. There is a lot of good stuff here and atomic PRs for the individual bits would be welcome.

**Pull request closed without merging**
